# Extração de Dados

pip install pandera

In [77]:
import pandas as pd
import numpy as np
import chardet
import pandera as pa

In [78]:
df = pd.read_csv('ocorrencias.csv', sep=',')
df

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,****,3/1/2010,12:00:00,0
1,40349,40349,INCIDENTE,BEL�M,PA,SBBE,3/1/2010,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,3/1/2010,3:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,4/1/2010,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,5/1/2010,19:25:00,0
...,...,...,...,...,...,...,...,...,...
6109,80245,80245,INCIDENTE,RECIFE,PE,SBRF,15/08/2021,15:05:00,0
6110,80247,80247,INCIDENTE,PORTO VELHO,RO,SBPV,16/08/2021,2:30:00,0
6111,80251,80251,INCIDENTE,BEL�M,PA,SBBE,17/08/2021,15:45:00,0
6112,80257,80257,ACIDENTE,DOM AQUINO,MT,****,18/08/2021,16:00:00,0
6113,80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,18/08/2021,12:45:00,0

In [79]:
with open('ocorrencias.csv', 'rb') as rawdata: 
    result = chardet.detect(rawdata.read(6000))
print(result)

{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}

In [80]:
df = pd.read_csv('ocorrencias.csv', encoding='ISO-8859-1')
df

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,****,3/1/2010,12:00:00,0
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,3/1/2010,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,3/1/2010,3:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,4/1/2010,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,5/1/2010,19:25:00,0
...,...,...,...,...,...,...,...,...,...
6109,80245,80245,INCIDENTE,RECIFE,PE,SBRF,15/08/2021,15:05:00,0
6110,80247,80247,INCIDENTE,PORTO VELHO,RO,SBPV,16/08/2021,2:30:00,0
6111,80251,80251,INCIDENTE,BELÉM,PA,SBBE,17/08/2021,15:45:00,0
6112,80257,80257,ACIDENTE,DOM AQUINO,MT,****,18/08/2021,16:00:00,0
6113,80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,18/08/2021,12:45:00,0

In [81]:
df.dtypes

codigo_ocorrencia            int64
codigo_ocorrencia2           int64
ocorrencia_classificacao    object
ocorrencia_cidade           object
ocorrencia_uf               object
ocorrencia_aerodromo        object
ocorrencia_dia              object
ocorrencia_hora             object
total_recomendacoes          int64
dtype: object

# A coluna ocorrencia_dia está como 'object' e precisamos converte-la para o tipo data.

In [82]:
df = pd.read_csv('ocorrencias.csv', encoding='ISO-8859-1', parse_dates=['ocorrencia_dia'])
df

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,****,2010-03-01,12:00:00,0
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-03-01,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-03-01,3:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,2010-04-01,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-05-01,19:25:00,0
...,...,...,...,...,...,...,...,...,...
6109,80245,80245,INCIDENTE,RECIFE,PE,SBRF,2021-08-15,15:05:00,0
6110,80247,80247,INCIDENTE,PORTO VELHO,RO,SBPV,2021-08-16,2:30:00,0
6111,80251,80251,INCIDENTE,BELÉM,PA,SBBE,2021-08-17,15:45:00,0
6112,80257,80257,ACIDENTE,DOM AQUINO,MT,****,2021-08-18,16:00:00,0
6113,80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,2021-08-18,12:45:00,0

In [83]:
df.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
dtype: object

In [84]:
df.ocorrencia_dia.dt.month

0       3
1       3
2       3
3       4
4       5
       ..
6109    8
6110    8
6111    8
6112    8
6113    8
Name: ocorrencia_dia, Length: 6114, dtype: int64

In [85]:
df.ocorrencia_dia.head()

0   2010-03-01
1   2010-03-01
2   2010-03-01
3   2010-04-01
4   2010-05-01
Name: ocorrencia_dia, dtype: datetime64[ns]

![](ocorrencia_dia.PNG)

In [86]:
# Como podemos perceber na imagem acima o dia esta na frente do mês, 
# vamos efetuar sua correção com o parametro 'dayfirst'

In [87]:
df = pd.read_csv('ocorrencias.csv', encoding='ISO-8859-1', parse_dates=['ocorrencia_dia'], dayfirst=True)
df.ocorrencia_dia.head()

0   2010-01-03
1   2010-01-03
2   2010-01-03
3   2010-01-04
4   2010-01-05
Name: ocorrencia_dia, dtype: datetime64[ns]

# Limpeza de Dados

In [88]:
df.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,****,2010-01-03,12:00:00,0
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,3:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,2010-01-04,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0

In [89]:
np.unique(df['ocorrencia_uf'])

array(['***', 'AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA',
       'MG', 'MS', 'MT', 'PA', 'PB', 'PE', 'PI', 'PR', 'RJ', 'RN', 'RO',
       'RR', 'RS', 'SC', 'SE', 'SP', 'TO'], dtype=object)

In [90]:
np.unique(df['ocorrencia_aerodromo'])

array(['###!', '####', '****', '*****', '5JTI', '9PAA', '9PBS', '9PFC',
       '9PFX', '9PHD', '9PSD', 'SBAE', 'SBAN', 'SBAQ', 'SBAR', 'SBAT',
       'SBAU', 'SBBE', 'SBBH', 'SBBI', 'SBBP', 'SBBQ', 'SBBR', 'SBBU',
       'SBBV', 'SBBW', 'SBBZ', 'SBCA', 'SBCB', 'SBCF', 'SBCG', 'SBCJ',
       'SBCP', 'SBCR', 'SBCT', 'SBCX', 'SBCY', 'SBCZ', 'SBDN', 'SBEG',
       'SBEK', 'SBFE', 'SBFI', 'SBFL', 'SBFN', 'SBFS', 'SBFZ', 'SBGL',
       'SBGO', 'SBGP', 'SBGR', 'SBGV', 'SBGW', 'SBHT', 'SBIH', 'SBIL',
       'SBIP', 'SBIT', 'SBIZ', 'SBJA', 'SBJC', 'SBJD', 'SBJF', 'SBJI',
       'SBJP', 'SBJR', 'SBJU', 'SBJV', 'SBKG', 'SBKP', 'SBLE', 'SBLJ',
       'SBLO', 'SBMA', 'SBMD', 'SBME', 'SBMG', 'SBMK', 'SBML', 'SBMO',
       'SBMQ', 'SBMS', 'SBMT', 'SBMY', 'SBNF', 'SBNM', 'SBNT', 'SBNV',
       'SBPA', 'SBPB', 'SBPC', 'SBPF', 'SBPJ', 'SBPK', 'SBPL', 'SBPN',
       'SBPP', 'SBPR', 'SBPS', 'SBPV', 'SBQV', 'SBRB', 'SBRD', 'SBRF',
       'SBRJ', 'SBRP', 'SBSG', 'SBSJ', 'SBSL', 'SBSM', 'SBSN', 'SBSP',
       'SBSR', 'SBST', 'SBSV', 'SBTA', 'SBTD', 'SBTE', 'SBTF', 'SBTK',
       'SBTR', 'SBTT', 'SBTV', 'SBUA', 'SBUF', 'SBUL', 'SBUR', 'SBUY',
       'SBVG', 'SBVH', 'SBVT', 'SBZM', 'SDAA', 'SDAG', 'SDAI', 'SDAM',
       'SDBA', 'SDBB', 'SDBK', 'SDBN', 'SDBV', 'SDCD', 'SDCO', 'SDDN',
       'SDDQ', 'SDED', 'SDEE', 'SDEH', 'SDEM', 'SDEN', 'SDET', 'SDGR',
       'SDHP', 'SDHU', 'SDIG', 'SDIH', 'SDIM', 'SDIO', 'SDIP', 'SDJA',
       'SDJB', 'SDJC', 'SDJL', 'SDJO', 'SDKE', 'SDKH', 'SDLL', 'SDLO',
       'SDLY', 'SDLZ', 'SDMC', 'SDMH', 'SDMJ', 'SDMM', 'SDMV', 'SDNB',
       'SDNE', 'SDNH', 'SDNI', 'SDOI', 'SDOR', 'SDOW', 'SDPA', 'SDPG',
       'SDPN', 'SDPW', 'SDPY', 'SDQG', 'SDRE', 'SDRK', 'SDRS', 'SDRV',
       'SDSC', 'SDTB', 'SDTF', 'SDTI', 'SDTK', 'SDTO', 'SDUB', 'SDUL',
       'SDVE', 'SDVG', 'SDVH', 'SDVI', 'SDVK', 'SDVL', 'SDVO', 'SDWC',
       'SDWU', 'SDWV', 'SDXF', 'SDYF', 'SDYJ', 'SDYW', 'SDZX', 'SIBH',
       'SIBO', 'SIBX', 'SIFC', 'SIFH', 'SIFV', 'SIJG', 'SIJY', 'SIKC',
       'SILC', 'SILT', 'SIMB', 'SIMQ', 'SING', 'SION', 'SIPB', 'SIPO',
       'SIPU', 'SIPY', 'SIQE', 'SIQH', 'SIQK', 'SIRI', 'SIRS', 'SISY',
       'SIVB', 'SIVQ', 'SIVU', 'SIXD', 'SIXE', 'SJAH', 'SJBH', 'SJBM',
       'SJBX', 'SJBY', 'SJCY', 'SJDU', 'SJFM', 'SJFU', 'SJGL', 'SJHG',
       'SJHR', 'SJIF', 'SJIJ', 'SJLO', 'SJLU', 'SJLY', 'SJNP', 'SJNQ',
       'SJOG', 'SJPT', 'SJQN', 'SJRG', 'SJTO', 'SJVL', 'SJVO', 'SJWQ',
       'SJXM', 'SJYG', 'SJYR', 'SNAG', 'SNAL', 'SNAS', 'SNAU', 'SNAZ',
       'SNBA', 'SNBG', 'SNBO', 'SNBR', 'SNBS', 'SNCJ', 'SNCL', 'SNCT',
       'SNCV', 'SNCW', 'SNCX', 'SNDC', 'SNDH', 'SNDP', 'SNDR', 'SNDT',
       'SNDU', 'SNDV', 'SNEJ', 'SNEM', 'SNFE', 'SNFJ', 'SNFS', 'SNFX',
       'SNGA', 'SNGG', 'SNGQ', 'SNGS', 'SNGU', 'SNGV', 'SNGX', 'SNHB',
       'SNHE', 'SNHH', 'SNIG', 'SNIT', 'SNIZ', 'SNJD', 'SNJI', 'SNJK',
       'SNJN', 'SNJO', 'SNJR', 'SNKB', 'SNKE', 'SNKF', 'SNKH', 'SNKI',
       'SNKK', 'SNLF', 'SNLM', 'SNLO', 'SNMA', 'SNMD', 'SNME', 'SNMH',
       'SNMU', 'SNMX', 'SNNL', 'SNOD', 'SNOF', 'SNOG', 'SNPA', 'SNPC',
       'SNPD', 'SNPJ', 'SNPX', 'SNPY', 'SNQV', 'SNQX', 'SNRP', 'SNRU',
       'SNSG', 'SNSH', 'SNSW', 'SNTF', 'SNTO', 'SNTY', 'SNUN', 'SNUZ',
       'SNVB', 'SNVC', 'SNVR', 'SNVS', 'SNWC', 'SNWS', 'SNXI', 'SNXR',
       'SNXT', 'SNXW', 'SNYE', 'SNYP', 'SNYR', 'SNYS', 'SNZA', 'SSAC',
       'SSAK', 'SSAQ', 'SSAU', 'SSAY', 'SSBG', 'SSBL', 'SSBN', 'SSBR',
       'SSCD', 'SSCE', 'SSCF', 'SSCK', 'SSCL', 'SSCN', 'SSCP', 'SSCR',
       'SSCT', 'SSDK', 'SSDO', 'SSDP', 'SSER', 'SSFB', 'SSFC', 'SSFE',
       'SSGA', 'SSGB', 'SSGG', 'SSGP', 'SSGX', 'SSHS', 'SSIE', 'SSIJ',
       'SSIQ', 'SSJA', 'SSJI', 'SSJL', 'SSKG', 'SSKK', 'SSKM', 'SSKS',
       'SSKT', 'SSKW', 'SSKZ', 'SSLT', 'SSMH', 'SSMW', 'SSNB', 'SSNG',
       'SSNH', 'SSNV', 'SSOG', 'SSOK', 'SSOL', 'SSOS', 'SSPB', 'SSPG',
       'SSPI', 'SSPL', 'SSPO', 'SSPQ', 'SSPS', 'SSPV', 'SSPX', 'SSQI',
       'SSQT', 'SSQZ', 'SSRA', 'SSRS', 'SSRZ', 'SSSB', 'SSSC', 'SSSE',
       'SSSS', 'SSSZ', 'SSTH', 'SSTL', 'SSUB', 'SSUL', 'SSUV', 'SSVA',
       'SSVN', 'SSXO', 'SSZL', 'SSZR', 'SSZW', 'SWAQ', 'SWBB', 'SWBE',
       'SWCA', 'SWCZ', 'SWDC', 'SWEF', 'SWEI', 'SWEJ', 'SWEK', 'SWEN',
       'SWEW', 'SWFN', 'SWFR', 'SWFV', 'SWFX', 'SWGC', 'SWGI', 'SWGN',
       'SWGP', 'SWHP', 'SWIN', 'SWIT', 'SWJN', 'SWJP', 'SWJW', 'SWKC',
       'SWKO', 'SWKT', 'SWLB', 'SWLC', 'SWLV', 'SWMO', 'SWMV', 'SWMW',
       'SWMZ', 'SWNB', 'SWNH', 'SWNK', 'SWNO', 'SWNS', 'SWOB', 'SWON',
       'SWOZ', 'SWPA', 'SWPD', 'SWPI', 'SWPQ', 'SWPY', 'SWQI', 'SWRD',
       'SWRO', 'SWRW', 'SWRZ', 'SWSI', 'SWSL', 'SWTS', 'SWUI', 'SWUQ',
       'SWUV', 'SWUZ', 'SWVC', 'SWVI', 'SWVR', 'SWVW', 'SWVZ', 'SWXQ',
       'SWXV', 'SWYH', 'SWYV'], dtype=object)

Como podemos verificar temos as seguintes inconsistentes ###!, ####, ****, *****, **, NULL

Agora vamos carregar nossos dados já executando a limpeza e validação em poucas linhas de comando

In [91]:
valores_ausentes = ['###!', '####', '****', '*****', '***', '**', 'NULL']
df = pd.read_csv('ocorrencias.csv', encoding='ISO-8859-1', parse_dates=['ocorrencia_dia'], dayfirst=True, na_values=valores_ausentes)
df.head(10)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,3:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
5,39807,39807,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0
6,40215,40215,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2
9,39711,39711,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0

# Validação

Agora vamos validar com o pacote pandera nosso Data Frame

In [92]:
schema = pa.DataFrameSchema(
    {
       'codigo_ocorrencia':pa.Column(pa.Int),
        'codigo_ocorrencia2':pa.Column(pa.Int),
        'ocorrencia_classificacao':pa.Column(pa.String),
        'ocorrencia_cidade':pa.Column(pa.String),
        'ocorrencia_uf':pa.Column(pa.String, pa.Check.str_length(2,2), nullable=True),
        'ocorrencia_aerodromo':pa.Column(pa.String, nullable=True),
        'ocorrencia_dia':pa.Column(pa.DateTime),
        'ocorrencia_hora':pa.Column(pa.String, pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9]):([0-5][0-9])?$'), nullable=True),
        'total_recomendacoes':pa.Column(pa.Int)
    }
)

In [93]:
schema.validate(df)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,3:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
...,...,...,...,...,...,...,...,...,...
6109,80245,80245,INCIDENTE,RECIFE,PE,SBRF,2021-08-15,15:05:00,0
6110,80247,80247,INCIDENTE,PORTO VELHO,RO,SBPV,2021-08-16,2:30:00,0
6111,80251,80251,INCIDENTE,BELÉM,PA,SBBE,2021-08-17,15:45:00,0
6112,80257,80257,ACIDENTE,DOM AQUINO,MT,NaN,2021-08-18,16:00:00,0
6113,80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,2021-08-18,12:45:00,0

# Transformação

Vamos unir as colunas ocorrencia dia e hora para facilitar seu armazenamento

In [94]:
df['ocorrencia_dia_hora'] = pd.to_datetime(df.ocorrencia_dia.astype(str) + ' ' + df.ocorrencia_hora)
df.head(10)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0,2010-01-03 12:00:00
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0,2010-01-03 11:05:00
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,3:00:00,0,2010-01-03 03:00:00
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0,2010-01-04 17:30:00
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0,2010-01-05 19:25:00
5,39807,39807,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0,2010-01-06 17:53:00
6,40215,40215,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0,2010-01-07 18:40:00
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3,2010-01-09 12:30:00
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2,2010-01-10 23:15:00
9,39711,39711,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0,2010-01-10 20:00:00

Agora vamos remover a coluna 'ocorrencia_dia' e 'ocorrencia_hora' pois elas já foram agurpadas em uma só

In [95]:
df.drop(columns=['ocorrencia_dia', 'ocorrencia_hora'], inplace=True)
df.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,total_recomendacoes,ocorrencia_dia_hora
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,0,2010-01-03 12:00:00
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,0,2010-01-03 11:05:00
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,0,2010-01-03 03:00:00
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,0,2010-01-04 17:30:00
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,0,2010-01-05 19:25:00

# Salvando os dados

Vamos atribuir a um arquivo '.csv' para depois efetuarmos seu carregamento

In [99]:
df.to_csv('ocorrencia_etl.csv', encoding='latin1', na_rep='N/A', index=None, date_format='%d/%m/%Y %H:%M')